[tool.poetry]
name = "guardrails"
version = "0.2.7"
description = "Adding guardrails to large language models."
authors = ["Guardrails AI <contact@guardrailsai.com>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.9.3"
openai = "<=0.28.1"
rich = "^13.6.0"
eliot = "^1.15.0"
eliot-tree = "^21.0.0"
pydantic = "1.10.9"
typer = "^0.9.0"
griffe = "^0.36.9"
tenacity = ">=8.1.0"
regex = "^2023.10.3"
rstr = "^3.2.2"
typing-extensions = "^4.8.0"
python-dateutil = "^2.8.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
black = "22.12.0"
isort = ">=5.12.0"
flake8 = ">=3.8.4"
docformatter = ">=1.4"
pytest-cov = ">=2.10.1"
pre-commit = ">=2.9.3"
twine = "^4.0.2"
pytest-mock = "^3.12.0"
pypdfium2 = "^4.23.1"
pyright = "^1.1.334"
lxml-stubs = "^0.4.0"


[tool.poetry.group.sql]
optional = true

[tool.poetry.group.sql.dependencies]
sqlvalidator = "^0.0.20"
sqlalchemy = ">=2.0.9"
sqlglot = "^19.0.3"


[tool.poetry.group.summary]
optional = true

[tool.poetry.group.summary.dependencies]
thefuzz = "^0.20.0"
nltk = "^3.8.1"


[tool.poetry.group.vectordb]
optional = true

[tool.poetry.group.vectordb.dependencies]
faiss-cpu = "^1.7.4"
tiktoken = "^0.5.1"
numpy = ">=1.24"


[tool.poetry.group.profanity]
optional = true

[tool.poetry.group.profanity.dependencies]
alt-profanity-check = "^1.3.1"


[tool.poetry.group.detect-secrets]
optional = true

[tool.poetry.group.detect-secrets.dependencies]
detect-secrets = "^1.4.0"


[tool.poetry.group.manifest]
optional = true

[tool.poetry.group.manifest.dependencies]
manifest-ml = "^0.1.8"


[tool.poetry.group.critique]
optional = true

[tool.poetry.group.critique.dependencies]
inspiredco = "^0.0.2"


[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocstrings = {extras = ["python"], version = "^0.23.0"}
mkdocs-jupyter = ">=0.23"
mkdocs-material = "^9.4.8"
mknotebooks = "^0.8.0"
griffe = "^0.36.9"
pillow = "^10.1.0"
cairosvg = "^2.7.1"
mkdocs-glightbox = "^0.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
