blank_issues_enabled: false
contact_links:
  - name: Guardrails Documentation
    url: https://www.guardrailsai.com/docs
    about: Check our documentation for answers to common questions and usage guides.
  - name: Guardrails Hub
    url: https://hub.guardrailsai.com/
    about: Explore pre-built validators and guards for specific types of risks.
  - name: GitHub Discussions
    url: https://github.com/guardrails-ai/guardrails/discussions
    about: Ask questions and discuss with other community members about Guardrails.
  - name: Join our Discord Community
    url: https://discord.com/invite/gw4cR9QvYE
    about: Connect with other Guardrails users and get real-time support.